variables : 
    IMAGE_NAME : mistyCode/springbootapp
    IMAGE_TAG : latest 



build_image : 
    image : docker:20.10.16
    services : 
        -docker:20.10.16-dind
    variables : 
        DOCKER_TLS_CERTDIR : "/certs"
    before_script : 
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
    script :
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
    only :
        - main
